### ISSUE TITLE
make hours a yaml file (+ templates)

### ISSUE THREAD

**Issue by bryfry** [alta3/somesaturday#6]
- read yaml file for shop hours and compile template using parsed values from hours.yaml
- turn all pages into a template and make the sidebar use the hours values

**Comment by bryfry** [comment]
turn index.html into the template that uses these values

**Comment by bryfry** [comment]
probably will need to move index to a /templates folder? or not not sure.

**Comment by sfeeser** [comment]
Hours are on a common format template, easy to edit that way.
